version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jee
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306

